#!/bin/sh

# Usage: build has_native

set -e 
LOC=`dirname $0`

. $LOC/pkg-builder

NATIVE=$1

add lib pkg/META                
add lib src/uucd.mli
add lib src/uucd.cmti
add lib src/uucd.cmi
add lib src/uucd.cmx
add lib src/uucd.cma
add lib src/uucd.a
add lib src/uucd.cmxa
add lib src/uucd.cmxs

add doc README.md
add doc CHANGES.md

build
install uucd
